# Generated by Django 3.2.6 on 2021-08-22 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=60, unique=True)),
                ('mime_type', models.CharField(max_length=40)),
                ('date_of_upload', models.DateTimeField()),
                ('date_of_recording', models.DateTimeField()),
                ('date_of_recording_end', models.DateTimeField()),
                ('state', models.CharField(max_length=20)),
                ('storage_link', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('hash', models.CharField(default='', max_length=400)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=40, unique=True)),
                ('date_of_recording', models.DateTimeField()),
                ('date_of_creation', models.DateTimeField()),
                ('storage_link', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('title', models.CharField(default='', max_length=250)),
                ('hash', models.CharField(default='', max_length=400)),
                ('audio_record_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml.audiorecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=250)),
                ('added', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDocumentReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml.document')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleCanViewDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
